package com.deepecho.mobile.lyrics

import android.text.Html
import com.deepecho.mobile.data.Song
import com.deepecho.mobile.net.Net
import okhttp3.Request
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.concurrent.ConcurrentHashMap

/**
 * Uses captions attached to the ACTUAL YouTube upload as a lightweight audio-grounded signal.
 * Captions are not treated as perfect lyrics. They are a verification/alignment source only.
 */
object CaptionResolver {
    private data class Entry(val at: Long, val lines: List<CaptionLine>)
    private val cache = ConcurrentHashMap<String, Entry>()
    private const val TTL = 6 * 60 * 60_000L

    fun resolve(song: Song, forceFresh: Boolean = false): List<CaptionLine> {
        if (!song.url.startsWith("http", true)) return emptyList()
        val now = System.currentTimeMillis()
        if (!forceFresh) {
            cache[song.url]?.let { if (now - it.at < TTL) return it.lines }
        }
        val lines = runCatching { fetch(song) }.getOrDefault(emptyList())
        cache[song.url] = Entry(now, lines)
        return lines
    }

    private fun fetch(song: Song): List<CaptionLine> {
        val info = StreamInfo.getInfo(ServiceList.YouTube, song.url)
        val streams = info.subtitles
        if (streams.isEmpty()) return emptyList()

        // Prefer real captions over auto-generated, and VTT over other formats because its timing
        // is straightforward and NewPipe's YouTube extractor exposes it reliably.
        val ranked = streams.sortedWith(
            compareBy<SubtitlesStream> { if (it.isAutoGenerated) 1 else 0 }
                .thenBy { if (it.format == MediaFormat.VTT) 0 else 1 }
        )

        for (stream in ranked.take(8)) {
            val body = runCatching {
                if (stream.isUrl) {
                    val req = Request.Builder().url(stream.content).header("User-Agent", Net.UA).build()
                    Net.client.newCall(req).execute().use { r -> if (r.isSuccessful) r.body?.string() else null }
                } else stream.content
            }.getOrNull().orEmpty()
            if (body.isBlank()) continue
            val parsed = when {
                stream.format == MediaFormat.VTT || body.trimStart().startsWith("WEBVTT") -> parseVtt(body, stream)
                body.contains("<text", true) -> parseTimedTextXml(body, stream)
                else -> emptyList()
            }
            if (parsed.size >= 2) return parsed
        }
        return emptyList()
    }

    private fun parseVtt(raw: String, stream: SubtitlesStream): List<CaptionLine> {
        val out = ArrayList<CaptionLine>()
        val lines = raw.replace("\r\n", "\n").replace('\r', '\n').lines()
        var i = 0
        while (i < lines.size) {
            val line = lines[i].trim()
            val timing = if (line.contains("-->")) line else lines.getOrNull(i + 1)?.trim().orEmpty().takeIf { it.contains("-->") }
            if (timing == null) { i++; continue }
            if (!line.contains("-->")) i++
            val parts = timing.split("-->", limit = 2)
            val start = parseTimestamp(parts.getOrNull(0).orEmpty().trim().substringBefore(' '))
            val end = parseTimestamp(parts.getOrNull(1).orEmpty().trim().substringBefore(' '))
            i++
            val payload = StringBuilder()
            while (i < lines.size && lines[i].isNotBlank()) {
                if (payload.isNotEmpty()) payload.append(' ')
                payload.append(lines[i].trim())
                i++
            }
            val text = cleanCaptionText(payload.toString())
            if (start >= 0 && text.isMeaningfulCaption()) {
                out += CaptionLine(
                    startMs = start,
                    endMs = if (end > start) end else start + 2_500L,
                    text = text,
                    languageTag = stream.languageTag,
                    autoGenerated = stream.isAutoGenerated
                )
            }
            i++
        }
        return cleanRollingCaptions(out)
    }

    private fun parseTimedTextXml(raw: String, stream: SubtitlesStream): List<CaptionLine> {
        val tag = Regex("""<text\s+([^>]*)>(.*?)</text>""", setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL))
        val attr = Regex("""(start|dur)=\"([^\"]+)\"""")
        val out = ArrayList<CaptionLine>()
        for (m in tag.findAll(raw)) {
            val attrs = attr.findAll(m.groupValues[1]).associate { it.groupValues[1] to it.groupValues[2] }
            val start = (attrs["start"]?.toDoubleOrNull()?.times(1000))?.toLong() ?: continue
            val dur = (attrs["dur"]?.toDoubleOrNull()?.times(1000))?.toLong() ?: 2_500L
            val text = cleanCaptionText(m.groupValues[2])
            if (text.isMeaningfulCaption()) {
                out += CaptionLine(start, start + dur.coerceAtLeast(250L), text, stream.languageTag, stream.isAutoGenerated)
            }
        }
        return cleanRollingCaptions(out)
    }

    private fun cleanRollingCaptions(input: List<CaptionLine>): List<CaptionLine> {
        if (input.isEmpty()) return input
        val out = ArrayList<CaptionLine>()
        var lastNorm = ""
        for (line in input.sortedBy { it.startMs }) {
            val norm = LyricsMetadata.normalizeText(line.text)
            if (norm.isBlank()) continue
            // YouTube auto-captions sometimes repeat an expanding rolling sentence. Keep the newer
            // cue only when it contributes substantial new text; otherwise avoid duplicate lyrics.
            if (lastNorm.isNotBlank() && (norm == lastNorm || (norm.startsWith(lastNorm) && norm.length - lastNorm.length < 7))) {
                continue
            }
            if (out.isNotEmpty() && LyricsMetadata.tokenSimilarity(out.last().text, line.text) > 0.94 && line.startMs - out.last().startMs < 1_200L) {
                continue
            }
            out += line
            lastNorm = norm
        }
        return out
    }

    private fun parseTimestamp(value: String): Long {
        val bits = value.split(':')
        return runCatching {
            when (bits.size) {
                2 -> {
                    val min = bits[0].toLong()
                    val sec = bits[1].replace(',', '.').toDouble()
                    (min * 60_000L + sec * 1000.0).toLong()
                }
                3 -> {
                    val hour = bits[0].toLong()
                    val min = bits[1].toLong()
                    val sec = bits[2].replace(',', '.').toDouble()
                    (hour * 3_600_000L + min * 60_000L + sec * 1000.0).toLong()
                }
                else -> -1L
            }
        }.getOrDefault(-1L)
    }

    private fun cleanCaptionText(raw: String): String {
        val stripped = raw
            .replace(Regex("""<c(?:\.[^>]*)?>|</c>|<v[^>]*>|</v>|<[^>]+>""", RegexOption.IGNORE_CASE), " ")
            .replace(Regex("""\{\\an\d+}"""), " ")
            .replace(Regex("""\s+"""), " ")
            .trim()
        return Html.fromHtml(stripped, Html.FROM_HTML_MODE_LEGACY).toString()
            .replace(Regex("""\s+"""), " ")
            .trim()
    }

    private fun String.isMeaningfulCaption(): Boolean {
        val n = LyricsMetadata.normalizeText(this)
        if (n.length < 2) return false
        val bracketOnly = trim().matches(Regex("""^[\[(].{1,40}[\)\]]$"""))
        if (bracketOnly) return false
        val noise = setOf("music", "applause", "instrumental", "foreign", "laughter", "cheering")
        return n !in noise
    }
}
