package com.deepecho.mobile.lyrics

import com.deepecho.mobile.net.Lyrics

data class LyricsCandidate(
    val provider: String,
    val title: String,
    val artist: String,
    val album: String?,
    val durationSec: Double,
    val lyrics: Lyrics,
    val score: CandidateScore,
    val exactLookup: Boolean = false,
    val id: String = "",
    /** Provider-side confidence only; DeepEcho still performs its own metadata/audio checks. */
    val providerConfidence: Int = 100,
    /** True when provider timing/text must be grounded against the actual playing upload first. */
    val requiresAudioVerification: Boolean = false
)

data class AudioVerification(
    val available: Boolean,
    val agreement: Int,
    val timingAgreement: Int,
    val firstVocalOnsetMs: Long?,
    val suspicious: Boolean,
    val reason: String,
    val captions: List<CaptionLine> = emptyList()
)

data class CaptionLine(
    val startMs: Long,
    val endMs: Long,
    val text: String,
    val languageTag: String = "",
    val autoGenerated: Boolean = false
)

data class AlignmentResult(
    val lyrics: Lyrics,
    val confidence: Int,
    val anchors: Int,
    val firstVocalOnsetMs: Long?
)
