package com.deepecho.mobile.lyrics

import com.deepecho.mobile.data.Song
import com.deepecho.mobile.net.Lyrics
import com.deepecho.mobile.net.YouTubeApi
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors
import java.util.concurrent.Future
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Optional, user-started live reader for actual lyric/lyrical videos.
 *
 * This is deliberately separate from LyricsOrchestrator.fetch(): the normal lyrics engine remains
 * the authority unless the user turns on "Read lyrics from video" on a strictly eligible lyric video.
 * Captions are preferred; OCR is only used when the current lyric video has no usable captions.
 */
object LyricsLiveVideoReader {
    data class Snapshot(
        val active: Boolean = false,
        val status: String = "",
        val lyrics: Lyrics? = null,
        val source: String = "",
        val failed: Boolean = false
    )

    private class Session(
        val cancelled: AtomicBoolean = AtomicBoolean(false),
        val positionMs: AtomicLong = AtomicLong(0L),
        var future: Future<*>? = null
    )

    private val executor = Executors.newSingleThreadExecutor { r ->
        Thread(r, "deepecho-live-video-lyrics").apply { isDaemon = true }
    }
    private val sessions = ConcurrentHashMap<String, Session>()
    private val _states = MutableStateFlow<Map<String, Snapshot>>(emptyMap())
    val states: StateFlow<Map<String, Snapshot>> = _states.asStateFlow()

    fun start(song: Song, startPositionMs: Long = 0L) {
        if (!LyricVideoEligibility.isEligible(song)) {
            publish(song.url, Snapshot(status = "Available only for lyric videos", failed = true))
            return
        }
        val existing = sessions[song.url]
        if (existing != null && existing.future?.isDone == false) {
            existing.positionMs.set(startPositionMs.coerceAtLeast(0L))
            return
        }

        stop(song.url, clearState = false)
        val session = Session(positionMs = AtomicLong(startPositionMs.coerceAtLeast(0L)))
        sessions[song.url] = session
        publish(song.url, Snapshot(active = true, status = "Checking video captions…"))
        session.future = executor.submit {
            try {
                if (session.cancelled.get()) return@submit

                val captions = runCatching { CaptionResolver.resolve(song, forceFresh = true) }.getOrDefault(emptyList())
                var provisionalCaptions: Lyrics? = null
                if (captions.size >= 2 && !session.cancelled.get()) {
                    val base = LyricsAlignmentEngine.fromCaptions(captions, null)
                    if (base != null) {
                        val manual = captions.none { it.autoGenerated }
                        val confidence = if (manual) 96 else 76
                        val captionLyrics = base.copy(
                            source = if (manual) "Video Captions • Live" else "Video Auto-Captions • Live",
                            verification = if (manual) "live_lyric_video_captions" else "live_lyric_video_auto_captions",
                            confidence = confidence,
                            audioConfidence = confidence,
                            alignmentConfidence = confidence,
                            verified = manual
                        )
                        publish(
                            song.url,
                            Snapshot(
                                active = true,
                                status = if (manual) "Video captions synced live" else "Auto-captions found • verifying video text…",
                                lyrics = captionLyrics,
                                source = "captions"
                            )
                        )
                        if (manual) return@submit
                        // Auto-captions can be badly wrong on fast rap/ragga. Keep them visible as a
                        // provisional fallback, but continue into on-screen OCR and prefer strong
                        // lyric-video text when it becomes available.
                        provisionalCaptions = captionLyrics
                    }
                }

                if (session.cancelled.get()) return@submit
                publish(
                    song.url,
                    Snapshot(
                        active = true,
                        status = "Reading on-screen lyrics…",
                        lyrics = provisionalCaptions,
                        source = if (provisionalCaptions != null) "captions+ocr" else "ocr"
                    )
                )
                val video = runCatching { YouTubeApi.resolveVideo(song.url, forceFresh = true) }.getOrNull()
                if (video == null || session.cancelled.get()) {
                    if (!session.cancelled.get() && provisionalCaptions != null) {
                        publish(
                            song.url,
                            Snapshot(
                                active = false,
                                status = "Using auto-captions • video text unavailable",
                                lyrics = provisionalCaptions,
                                source = "captions"
                            )
                        )
                    } else if (!session.cancelled.get()) {
                        publish(song.url, Snapshot(active = false, status = "Could not open lyric video", failed = true))
                    }
                    return@submit
                }

                var delivered = provisionalCaptions != null
                var ocrDelivered = false
                LyricsVideoOcrProcessor.extractLive(
                    directVideoUrl = video.url,
                    expectedDurationMs = song.durationSec * 1000L,
                    positionProvider = { session.positionMs.get() },
                    isCancelled = { session.cancelled.get() || Thread.currentThread().isInterrupted },
                    onUpdate = { lines ->
                        if (session.cancelled.get() || lines.size < 2) return@extractLive
                        // Do not replace a complete provisional caption timeline with only one or two
                        // freshly-read OCR fragments. Wait for enough on-screen evidence first.
                        if (provisionalCaptions != null && lines.size < 6) return@extractLive
                        val base = LyricsAlignmentEngine.fromCaptions(lines, null) ?: return@extractLive
                        val confidence = when {
                            lines.size >= 14 -> 91
                            lines.size >= 8 -> 87
                            lines.size >= 4 -> 82
                            else -> 76
                        }
                        delivered = true
                        ocrDelivered = true
                        publish(
                            song.url,
                            Snapshot(
                                active = true,
                                status = if (lines.size >= 8) "On-screen lyrics synced live" else "Reading next on-screen lyrics…",
                                lyrics = base.copy(
                                    source = "Video OCR • Live",
                                    verification = "live_lyric_video_ocr",
                                    confidence = confidence,
                                    audioConfidence = confidence,
                                    alignmentConfidence = confidence,
                                    verified = lines.size >= 8 && confidence >= 84
                                ),
                                source = "ocr"
                            )
                        )
                    }
                )
                if (!session.cancelled.get() && !delivered) {
                    publish(song.url, Snapshot(active = false, status = "Could not read lyrics from this video", source = "ocr", failed = true))
                } else if (!session.cancelled.get() && provisionalCaptions != null && !ocrDelivered) {
                    publish(
                        song.url,
                        Snapshot(
                            active = false,
                            status = "Using auto-captions • on-screen text not strong enough",
                            lyrics = provisionalCaptions,
                            source = "captions"
                        )
                    )
                }
            } catch (_: Throwable) {
                if (!session.cancelled.get()) {
                    publish(song.url, Snapshot(active = false, status = "Video lyrics reader stopped safely", failed = true))
                }
            } finally {
                sessions.remove(song.url, session)
            }
        }
    }

    fun updatePosition(songUrl: String, positionMs: Long) {
        sessions[songUrl]?.positionMs?.set(positionMs.coerceAtLeast(0L))
    }

    fun stop(songUrl: String, clearState: Boolean = true) {
        sessions.remove(songUrl)?.let { session ->
            session.cancelled.set(true)
            session.future?.cancel(true)
        }
        if (clearState) clear(songUrl)
    }

    private fun publish(songUrl: String, snapshot: Snapshot) {
        _states.value = _states.value.toMutableMap().apply { put(songUrl, snapshot) }
    }

    private fun clear(songUrl: String) {
        _states.value = _states.value.toMutableMap().apply { remove(songUrl) }
    }
}
