package com.deepecho.mobile.lyrics

import com.deepecho.mobile.data.Song
import com.deepecho.mobile.net.Lyrics

/**
 * Recovery stage used after provider verification fails.
 *
 * v1.12.3 deliberately uses only transcription evidence that is actually available today:
 * timed captions belonging to the exact playing upload. Auto-generated captions are treated as
 * ASR hypotheses and are refined conservatively. If the upload exposes no transcript/captions,
 * this class fails honestly rather than fabricating a local Whisper result that is not packaged.
 */
object LyricsTranscriptionFallback {
    data class Recovery(
        val lyrics: Lyrics,
        val repairMode: LyricsRepairMode,
        val transcriptKind: String,
        val changedTokens: Int
    )

    fun recover(song: Song, captions: List<CaptionLine>, referenceText: String? = null): Recovery? {
        if (captions.size < 2) return null
        val generated = LyricsAlignmentEngine.fromCaptions(captions, null) ?: return null
        val refined = LyricsTextRefiner.refine(generated, referenceText)
        val timingConfidence = refined.lyrics.alignmentConfidence
        val mode = LyricsRepairPlanner.choose(
            textConfidence = refined.textConfidence,
            timingConfidence = timingConfidence,
            hasUsableText = !refined.lyrics.plain.isNullOrBlank()
        )
        val auto = captions.count { it.autoGenerated } >= (captions.size / 2).coerceAtLeast(1)
        val source = if (auto) "Exact Lyrics • Upload transcription" else "Exact Lyrics • Upload captions"
        return Recovery(
            lyrics = refined.lyrics.copy(
                source = source + if (refined.changedTokens > 0) " • Text refined" else "",
                verification = if (auto) "upload_transcription_recovery" else "upload_caption_recovery",
                verified = !auto && refined.lyrics.alignmentConfidence >= 70,
                confidence = maxOf(refined.lyrics.confidence, if (auto) 64 else 80)
            ),
            repairMode = mode,
            transcriptKind = if (auto) "auto-generated upload transcript" else "creator upload captions",
            changedTokens = refined.changedTokens
        )
    }
}
