package com.deepecho.mobile.lyrics

import com.deepecho.mobile.net.LyricLine
import com.deepecho.mobile.net.LyricWord
import com.deepecho.mobile.net.Lyrics
import kotlin.math.abs

/** Piecewise caption/audio anchored timeline repair. */
object LyricsAlignmentEngine {
    private data class Anchor(val lineIndex: Int, val sourceMs: Long, val targetMs: Long, val score: Double)

    fun align(provider: Lyrics, captions: List<CaptionLine>): AlignmentResult? {
        val lines = provider.synced
        if (lines.size < 2 || captions.size < 2) return null

        val anchors = buildAnchors(lines, captions)
        if (anchors.isEmpty()) return null
        val strong = anchors.filter { it.score >= 0.48 }
        if (strong.isEmpty()) return null

        val reliableAnchors = monotonic(strong)
        val firstVocal = reliableAnchors.firstOrNull()?.targetMs ?: captions.firstOrNull()?.startMs
        val mappedLines = lines.mapIndexed { index, line ->
            val mapped = mapTime(index, line.timeMs, reliableAnchors).coerceAtLeast(0L)
            val original = line.timeMs
            val localRatio = localScaleFor(index, reliableAnchors)
            val correctedWords = if (line.words.isNotEmpty()) {
                line.words.map { word ->
                    val delta = (word.timeMs - original).coerceAtLeast(0L)
                    val adjustedDelta = (delta * localRatio).toLong()
                    word.copy(timeMs = (mapped + adjustedDelta).coerceAtLeast(mapped), timingConfidence = maxOf(word.timingConfidence, 60))
                }
            } else emptyList()
            line.copy(timeMs = mapped, words = correctedWords)
        }
        val corrected = ArrayList<LyricLine>(mappedLines.size)
        mappedLines.forEach { line ->
            val minTime = (corrected.lastOrNull()?.timeMs ?: -81L) + 80L
            val t = maxOf(line.timeMs, minTime)
            val words = line.words.map { word -> word.copy(timeMs = maxOf(word.timeMs, t)) }
            corrected += line.copy(timeMs = t, words = words)
        }

        val avg = (reliableAnchors.map { it.score }.average() * 100).toInt().coerceIn(1, 100)
        return AlignmentResult(
            lyrics = provider.copy(
                synced = corrected,
                estimatedSync = false,
                source = if (provider.source.contains("LRCLIB", true)) "LRCLIB • Re-aligned" else "${provider.source} • Re-aligned",
                verification = "audio_aligned",
                audioConfidence = maxOf(provider.audioConfidence, avg),
                alignmentConfidence = avg,
                firstVocalOnsetMs = firstVocal,
                verified = avg >= 55,
                confidence = maxOf(provider.confidence, avg)
            ),
            confidence = avg,
            anchors = reliableAnchors.size,
            firstVocalOnsetMs = firstVocal
        )
    }

    fun fromCaptions(captions: List<CaptionLine>, plainReference: String? = null): Lyrics? {
        if (captions.size < 2) return null
        val filtered = captions.filter { it.text.isNotBlank() }.take(320)
        if (filtered.size < 2) return null
        val lines = filtered.map { LyricLine(it.startMs, it.text) }
        val text = plainReference?.takeIf { it.isNotBlank() } ?: filtered.joinToString("\n") { it.text }
        val confidence = if (filtered.first().autoGenerated) 64 else 78
        return Lyrics(
            synced = lines,
            plain = text,
            estimatedSync = false,
            confidence = confidence,
            source = "Exact Lyrics • Captions",
            metadataConfidence = 0,
            audioConfidence = confidence,
            alignmentConfidence = confidence,
            verification = "caption_generated",
            firstVocalOnsetMs = filtered.first().startMs,
            verified = !filtered.first().autoGenerated,
            variant = null
        )
    }

    private fun buildAnchors(lines: List<LyricLine>, captions: List<CaptionLine>): List<Anchor> {
        val out = ArrayList<Anchor>()
        var minCaption = 0
        lines.forEachIndexed { index, line ->
            var bestIndex = -1
            var best = 0.0
            // Monotonic forward window keeps repeated choruses from randomly anchoring backwards.
            val end = minOf(captions.lastIndex, minCaption + 80)
            for (ci in minCaption..end) {
                val score = LyricsAudioVerifier.lineAgreement(line.text, captions[ci].text)
                val timingDistance = abs(line.timeMs - captions[ci].startMs)
                val adjusted = score - when {
                    timingDistance <= 8_000L -> 0.0
                    timingDistance <= 30_000L -> 0.03
                    timingDistance <= 90_000L -> 0.08
                    else -> 0.13
                }
                if (adjusted > best) { best = adjusted; bestIndex = ci }
            }
            if (bestIndex >= 0 && best >= 0.36) {
                out += Anchor(index, line.timeMs, captions[bestIndex].startMs, best.coerceIn(0.0, 1.0))
                minCaption = bestIndex
            }
        }
        return out
    }

    private fun monotonic(input: List<Anchor>): List<Anchor> {
        val out = ArrayList<Anchor>()
        for (a in input.sortedBy { it.lineIndex }) {
            if (out.isEmpty() || a.targetMs > out.last().targetMs + 80L) out += a
        }
        return out
    }

    private fun localScaleFor(index: Int, anchors: List<Anchor>): Double {
        val before = anchors.lastOrNull { it.lineIndex <= index }
        val after = anchors.firstOrNull { it.lineIndex > index }
        if (before != null && after != null) {
            val src = (after.sourceMs - before.sourceMs).toDouble()
            val dst = (after.targetMs - before.targetMs).toDouble()
            if (src > 250.0 && dst > 0.0) return (dst / src).coerceIn(0.70, 1.35)
        }
        return 1.0
    }

    private fun mapTime(index: Int, sourceMs: Long, anchors: List<Anchor>): Long {
        if (anchors.isEmpty()) return sourceMs
        val exact = anchors.firstOrNull { it.lineIndex == index }
        if (exact != null) return exact.targetMs
        val before = anchors.lastOrNull { it.lineIndex < index }
        val after = anchors.firstOrNull { it.lineIndex > index }
        return when {
            before != null && after != null && after.sourceMs > before.sourceMs -> {
                val ratio = ((sourceMs - before.sourceMs).toDouble() / (after.sourceMs - before.sourceMs).toDouble()).coerceIn(0.0, 1.0)
                (before.targetMs + (after.targetMs - before.targetMs) * ratio).toLong()
            }
            before != null -> sourceMs + (before.targetMs - before.sourceMs)
            after != null -> sourceMs + (after.targetMs - after.sourceMs)
            else -> sourceMs
        }
    }
}
