package com.deepecho.mobile.lyrics

/** Pure cleanup stage for OCR output; deliberately avoids dangerous global spelling replacements. */
object OcrLyricsCleaner {
    data class RawLine(
        val startMs: Long,
        val endMs: Long,
        val text: String,
        val centerYRatio: Float = 0.5f,
        val confidence: Int = 70
    )

    private val obviousUiNoise = Regex(
        "(?i)^(subscribe|follow|instagram|facebook|twitter|tiktok|official\\s+video|official\\s+audio|lyrics?|lyric\\s+video|copyright|all\\s+rights\\s+reserved|thanks\\s+for\\s+watching|like\\s+and\\s+subscribe)(\\b.*)?$"
    )

    fun clean(input: List<RawLine>): List<CaptionLine> {
        if (input.isEmpty()) return emptyList()
        val normalized = input.mapNotNull { line ->
            val text = normalizeSurface(line.text)
            if (!meaningful(text)) null else line.copy(text = text)
        }.sortedBy { it.startMs }
        if (normalized.isEmpty()) return emptyList()

        // Repeated stationary text over a large fraction of the video is usually a watermark/handle.
        val byText = normalized.groupBy { LyricsMetadata.normalizeText(it.text) }
        val watermarkKeys = byText.filter { (_, lines) ->
            if (lines.size < 4) return@filter false
            val span = (lines.maxOf { it.endMs } - lines.minOf { it.startMs }).coerceAtLeast(1L)
            val positions = lines.map { it.centerYRatio }
            val positionSpread = (positions.maxOrNull() ?: 0f) - (positions.minOrNull() ?: 0f)
            span >= 25_000L && positionSpread < 0.06f && (positions.average() < 0.16 || positions.average() > 0.88)
        }.keys

        val out = ArrayList<CaptionLine>()
        for (line in normalized) {
            val key = LyricsMetadata.normalizeText(line.text)
            if (key in watermarkKeys || obviousUiNoise.matches(line.text.trim())) continue
            val previous = out.lastOrNull()
            if (previous != null) {
                val sim = LyricsMetadata.tokenSimilarity(previous.text, line.text)
                if (sim >= 0.94 && line.startMs - previous.endMs <= 2_800L) {
                    out[out.lastIndex] = previous.copy(endMs = maxOf(previous.endMs, line.endMs))
                    continue
                }
            }
            out += CaptionLine(
                startMs = line.startMs.coerceAtLeast(0L),
                endMs = maxOf(line.endMs, line.startMs + 500L),
                text = line.text,
                languageTag = "ocr",
                autoGenerated = true
            )
        }
        return out.take(360)
    }

    private fun normalizeSurface(raw: String): String = raw
        .replace('|', 'I')
        .replace(Regex("[\\u200B-\\u200D\\uFEFF]"), "")
        .replace(Regex("\\s+"), " ")
        .trim()

    private fun meaningful(text: String): Boolean {
        val n = LyricsMetadata.normalizeText(text)
        if (n.length < 2) return false
        if (text.length > 150) return false
        val letters = text.count { it.isLetterOrDigit() }
        if (letters < 2) return false
        val symbols = text.count { !it.isLetterOrDigit() && !it.isWhitespace() }
        if (symbols > text.length * 0.55) return false
        return true
    }
}
